// Code generated by "stringer -type=Duration"; DO NOT EDIT.

package goMusic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WholeNote-32]
	_ = x[HalfNote-16]
	_ = x[QuarterNote-8]
	_ = x[EighthNote-4]
	_ = x[SixteenthNote-2]
	_ = x[ThirtySecondNote-1]
}

const (
	_Duration_name_0 = "ThirtySecondNoteSixteenthNote"
	_Duration_name_1 = "EighthNote"
	_Duration_name_2 = "QuarterNote"
	_Duration_name_3 = "HalfNote"
	_Duration_name_4 = "WholeNote"
)

var (
	_Duration_index_0 = [...]uint8{0, 16, 29}
)

func (i Duration) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Duration_name_0[_Duration_index_0[i]:_Duration_index_0[i+1]]
	case i == 4:
		return _Duration_name_1
	case i == 8:
		return _Duration_name_2
	case i == 16:
		return _Duration_name_3
	case i == 32:
		return _Duration_name_4
	default:
		return "Duration(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
