// Code generated by "stringer -type=Pitch"; DO NOT EDIT.

package goMusic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[G0-53]
	_ = x[G0Sharp-54]
	_ = x[A0-55]
	_ = x[A0Sharp-56]
	_ = x[B0-57]
	_ = x[C1-58]
	_ = x[C1Sharp-59]
	_ = x[D1-60]
	_ = x[D1Sharp-61]
	_ = x[E1-62]
	_ = x[F1-63]
	_ = x[F1Sharp-64]
	_ = x[G1-65]
	_ = x[G1Sharp-66]
	_ = x[A1-67]
	_ = x[A1Sharp-68]
	_ = x[B1-69]
	_ = x[C2-70]
	_ = x[C2Sharp-71]
	_ = x[D2-72]
	_ = x[D2Sharp-73]
	_ = x[E2-74]
	_ = x[F2-75]
	_ = x[F2Sharp-76]
	_ = x[G2-77]
	_ = x[G2Sharp-78]
}

const _Pitch_name = "G0G0SharpA0A0SharpB0C1C1SharpD1D1SharpE1F1F1SharpG1G1SharpA1A1SharpB1C2C2SharpD2D2SharpE2F2F2SharpG2G2Sharp"

var _Pitch_index = [...]uint8{0, 2, 9, 11, 18, 20, 22, 29, 31, 38, 40, 42, 49, 51, 58, 60, 67, 69, 71, 78, 80, 87, 89, 91, 98, 100, 107}

func (i Pitch) String() string {
	i -= 53
	if i < 0 || i >= Pitch(len(_Pitch_index)-1) {
		return "Pitch(" + strconv.FormatInt(int64(i+53), 10) + ")"
	}
	return _Pitch_name[_Pitch_index[i]:_Pitch_index[i+1]]
}
