// Code generated by "stringer -type=Scale"; DO NOT EDIT.

package shawzin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Chromatic-3]
}

const _Scale_name = "Chromatic"

var _Scale_index = [...]uint8{0, 9}

func (i Scale) String() string {
	i -= 3
	if i < 0 || i >= Scale(len(_Scale_index)-1) {
		return "Scale(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _Scale_name[_Scale_index[i]:_Scale_index[i+1]]
}
